name: StupidOCR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: "windows-2019"

    steps:
      - uses: actions/checkout@v4
        with:
          repository: "81NewArk/StupidOCR"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Build
        run: python -m PyInstaller StupidOCR.py -n StupidOCR -F
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: StupidOCR
          path: |
            dist/StupidOCR.exe
